const DB_NAME='game-hub-db';const DB_VERSION=1;const STORE='games';const CACHE='game-hub-files-v1';
const CATALOG_URL='./games_catalog.json';
const state={catalog:[],installed:new Map(),category:'All',query:'',online:navigator.onLine};
const $=s=>document.querySelector(s);const tpl=$('#gameCardTemplate');
function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id'});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function tx(mode,fn){const db=await openDb();return new Promise((res,rej)=>{const t=db.transaction(STORE,mode);const st=t.objectStore(STORE);const out=fn(st);t.oncomplete=()=>res(out);t.onerror=()=>rej(t.error)})}
const getAll=()=>tx('readonly',s=>new Promise(r=>{const q=s.getAll();q.onsuccess=()=>r(q.result)}));
const putGame=g=>tx('readwrite',s=>s.put(g));const delGame=id=>tx('readwrite',s=>s.delete(id));
const fmt=b=>`${(b/1024/1024).toFixed(b>1024*1024?1:2)} MB`;
async function init(){document.documentElement.dataset.theme=localStorage.theme||'dark';bindUi();await navigator.serviceWorker?.register('./service-worker.js');await refreshInstalled();await loadCatalog();render();}
function bindUi(){window.addEventListener('online',()=>{state.online=true;renderStatus();loadCatalog()});window.addEventListener('offline',()=>{state.online=false;renderStatus()});$('#themeToggle').onclick=()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.theme=next};$('#searchInput').oninput=e=>{state.query=e.target.value.toLowerCase();renderGames()};document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>route(b.dataset.route));$('#checkUpdatesBtn').onclick=checkUpdates}
function route(name){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===name));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.route===name));if(name==='storage')renderStorage();if(name==='library')renderLibrary()}
async function refreshInstalled(){state.installed=new Map((await getAll()).map(g=>[g.id,g]));}
async function loadCatalog(){showSkeleton(true);try{const r=await fetch(CATALOG_URL,{cache:'no-store'});state.catalog=await r.json();await checkUpdates(false)}catch{if(!state.catalog.length)state.catalog=[...state.installed.values()]}finally{showSkeleton(false);render()}}
function showSkeleton(on){$('#featuredSkeleton').innerHTML=on?'<div class="skeleton"></div><div class="skeleton"></div>':''}
function render(){renderStatus();renderFilters();renderGames();renderLibrary();renderStorage()}
function renderStatus(){$('#networkStatus').textContent=state.online?'Online: catalog sync on':'Offline: installed games only'}
function renderFilters(){const cats=['All',...new Set(state.catalog.flatMap(g=>g.categories||[]))];$('#categoryFilters').innerHTML=cats.map(c=>`<button class="chip ${state.category===c?'active':''}" data-cat="${c}">${c}</button>`).join('');document.querySelectorAll('.chip').forEach(c=>c.onclick=()=>{state.category=c.dataset.cat;renderFilters();renderGames()})}
function filtered(){return state.catalog.filter(g=>(state.category==='All'||(g.categories||[]).includes(state.category))&&(`${g.name} ${g.description}`.toLowerCase().includes(state.query)))}
function renderGames(){const grid=$('#gamesGrid');grid.innerHTML='';filtered().forEach(g=>grid.append(card(g)))}

function renderStorage(){const list=$('#storageList');const items=[...state.installed.values()];const total=items.reduce((sum,g)=>sum+(g.size||0),0);$('#totalStorage').textContent=fmt(total);list.innerHTML=items.length?'':'<p class="description" style="padding:14px">Installed game storage usage will appear here.</p>';items.forEach(g=>{const row=document.createElement('div');row.className='storage-row';row.innerHTML=`<div><strong>${g.name}</strong><p class="description">${fmt(g.size||0)} • installed ${new Date(g.installedAt).toLocaleDateString()}</p></div>`;row.append(btn('Delete','danger-btn',()=>uninstall(g.id)));list.append(row)})}
function renderLibrary(){const grid=$('#libraryGrid');grid.innerHTML='';const items=[...state.installed.values()];grid.innerHTML=items.length?'':'<p class="description">No games installed yet. Install a game from the Store while online.</p>';items.forEach(g=>grid.append(card(g,true)))}
function card(g,library=false){const n=tpl.content.cloneNode(true);const root=n.querySelector('.game-card');n.querySelector('.game-logo').src=g.logo||'assets/icon.svg';n.querySelector('.game-logo').alt=`${g.name} logo`;n.querySelector('h3').textContent=g.name;n.querySelector('.version').textContent=`v${g.version||'1.0.0'}`;n.querySelector('.description').textContent=g.description||'Offline game';n.querySelector('.meta-row').textContent=`${(g.categories||['Arcade']).join(' • ')} • ${g.size?fmt(g.size):'size after install'}`;const actions=n.querySelector('.actions');const installed=state.installed.get(g.id);const newer=installed&&g.version&&installed.version!==g.version;if(installed){actions.append(btn('Play','primary-btn',()=>play(installed)));if(newer)actions.append(btn('Update','soft-btn',()=>install(g)));actions.append(btn('Delete','danger-btn',()=>uninstall(installed.id)))}else if(!library){actions.append(btn('Install','primary-btn',()=>install(g),!state.online))}return root}
function btn(text,cls,fn,disabled=false){const b=document.createElement('button');b.textContent=text;b.className=cls;b.disabled=disabled;b.onclick=fn;return b}
async function install(game){const d=$('#installDialog');$('#dialogTitle').textContent=`Installing ${game.name}`;$('#dialogText').textContent='Downloading game assets to offline cache.';$('#installProgress').value=3;d.showModal();const files=game.files?.length?game.files:['index.html'];let done=0,total=0;const cache=await caches.open(CACHE);for(const file of files){const url=new URL(file,new URL(game.baseUrl,location.href)).toString();const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw new Error(`Missing ${url}`);const blob=await res.clone().blob();total+=blob.size;await cache.put(`/offline-games/${game.id}/${file}`,res);done++;$('#installProgress').value=Math.round(done/files.length*100)}const installed={...game,size:total,installedAt:new Date().toISOString(),entry:`/offline-games/${game.id}/${game.entry||'index.html'}`};await putGame(installed);await refreshInstalled();render();$('#dialogTitle').textContent='Ready to play';$('#dialogText').textContent=`${game.name} is available offline (${fmt(total)}).`}
async function uninstall(id){if(!confirm('Delete this game from offline storage?'))return;const cache=await caches.open(CACHE);for(const req of await cache.keys())if(new URL(req.url).pathname.startsWith(`/offline-games/${id}/`))await cache.delete(req);await delGame(id);await refreshInstalled();render()}
function play(g){location.href=g.entry}
async function checkUpdates(show=true){await refreshInstalled();const updates=state.catalog.filter(g=>state.installed.get(g.id)&&state.installed.get(g.id).version!==g.version).length;if(show)alert(updates?`${updates} update(s) available.`:'All installed games are current.');render()}
init().catch(err=>{console.error(err);alert(err.message)});
